version: '2'

services:
   web:
     image: ebuzaneli/buzza-server-apache2-php5 
     hostname: buzza-server-apache
     container_name: buzza-server-apache
     ports: 
       - "9090:80"
       - "4493:443"
     volumes:
       - /Users/eniomarcelobuzaneli/Documents/Docker/Docker-LAMP-PHP-5.6/www:/var/www/html
       - /Users/eniomarcelobuzaneli/Documents/Docker/Docker-LAMP-PHP-5.6/php/php.ini:/etc/php5/apache2/php.ini
     links:
       - db
     restart: always
     environment:
       - TZ=America/Campo_Grande
     depends_on:
        - db
     networks:
        - buzza-protocolo-network

   db:
      image: ebuzaneli/buzza-server-mysql:5.6
      hostname: buzza-server-mysql
      container_name: buzza-server-mysql
      ports:
         - "3307:3306"
      volumes:
         - /Users/eniomarcelobuzaneli/Documents/Docker/Docker-LAMP-PHP-5.6/mysql-data:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=123456
         - MYSQL_DATABASE=db_buzza
         - TZ=America/Campo_Grande
      restart: always
      networks:
         - buzza-protocolo-network

   phpmyadmin:
      image: ebuzaneli/buzza-phpmyadmin:latest 
      hostname: buzza-server-phpmyadmin
      container_name: buzza-server-phpmyadmin
      links:
         - db
      environment:
         PMA_HOST: db
         PMA_PORT: 3306
      ports:
         - '8082:80' 
      restart: always
      depends_on:
         - db
      networks:
         - buzza-protocolo-network

   ssh:
      image: ebuzaneli/buzza-server-ssh:latest 
      hostname: buzza-server-ssh
      container_name: buzza-server-ssh
      environment:
         - "SSH_USER=buzza"
         - "SSH_PASSWORD=102030" 
         - TZ=America/Campo_Grande
      volumes:
         - /Users/eniomarcelobuzaneli/Documents/Docker/Docker-LAMP-PHP-5.6/www:/var/www/html
      ports:
         - '2222:22'
      restart: always
      networks:
         - buzza-protocolo-network

networks:
   buzza-protocolo-network:
    driver: bridge


